name: Trigger Gitea Action

on:
  push:
    branches: [ main ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Gitea workflow_dispatch
        run: |
          curl -X POST 'https://gitea.lyra-on.top/api/v1/repos/lyra_phasma/phasmolysis-pebble-recall-deploy/actions/workflows/render-and-deploy.yml/dispatches' \
            --url-query 'access_token=${{ secrets.GITEA_ACCESS_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{"ref": "main"}'
